# Configuration stylua pour Neovim
column_width = 100
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferSingle"
call_parentheses = "Always"

# Autres options utiles
collapse_simple_statement = "Never"
